# 降落位置在地图坐标下的位置
# 需要根据实际地图再次进行测量
# 根据 index 索引 0 至 15 
# 0 位于 16 个点的左上角
# 15 位于 右下角
land_way_point:
  - [90.5 , 23 , 2.0]
  - [90.5 , 18 , 2.0]
  - [90.5 , 13 , 2.0]
  - [90.5 , 8 , 2.0] # 第一行

  - [88.5, 23 , 2.0]
  - [88.5, 18 , 2.0]
  - [88.5 , 13 , 2.0]
  - [88.5 , 8 , 2.0] # 第二行

  - [86.5 , 23 , 2.0]
  - [86.5 , 18 , 2.0]
  - [86.5 , 13, 2.0]
  - [86.5 , 8 , 2.0] # 第三行

  - [84.5 , 23 , 2.0]
  - [84.5 , 18 , 2.0]
  - [84.5 , 13 , 2.0]
  - [84.5 , 8 , 2.0] # 第三行
