first_target_pos:
- id: 1
  x: 14.0
  y: 10.9
  z: 4.4

- id: 2
  x: 14.0
  y: 4.9
  z: 4.4

- id: 3
  x: 14.0
  y: 8.9
  z: 4.4

- id: 4
  x: 14.0
  y: 14.9
  z: 4.4

- id: 5
  x: 14.0
  y: 12.9
  z: 4.4

- id: 6
  x: 14.0
  y: 6.9
  z: 4.4

rect_target_pos:
- id: 1
  x: 36.0
  y: 2.5
  z: 1.0

- id: 2
  x: 36.0
  y: 7.5
  z: 1.0

- id: 3
  x: 36.0
  y: 12.5
  z: 1.0

- id: 4
  x: 36.0
  y: 17.5
  z: 1.0

- id: 5
  x: 36.0
  y: 22.5
  z: 1.0

- id: 6
  x: 36.0
  y: 27.5
  z: 1.0

cross_rect_target_pos:
- id: 1
  x: 43.0
  y: 2.5
  z: 1.0

- id: 2
  x: 43.0
  y: 7.5
  z: 1.0

- id: 3
  x: 43.0
  y: 12.5
  z: 1.0

- id: 4
  x: 43.0
  y: 17.5
  z: 1.0

- id: 5
  x: 43.0
  y: 22.5
  z: 1.0

- id: 6
  x: 43.0
  y: 27.5
  z: 1.0

one_target_pos_0:

- x: 43.0
  y: 15.0
  z: 1.0

- x: 66.0
  y: 15.0
  z: 1.0

one_target_pos_1:

- x: 43.0
  y: 15.0
  z: 1.0

- x: 72.0
  y: 15.0
  z: 1.0

one_target_pos_2:

- x: 46.0
  y: 15.0
  z: 1.0

- x: 78.0
  y: 15.0
  z: 1.0

one_target_pos_3:

- x: 43.0
  y: 15.0
  z: 1.0

- x: 75.0
  y: 15.0
  z: 1.0

one_target_pos_4:

- x: 43.0
  y: 15.0
  z: 1.0

- x: 69.0
  y: 15.0
  z: 1.0

one_target_pos_5:

- x: 43.0
  y: 15.0
  z: 1.0

- x: 63.0
  y: 15.0
  z: 1.0